name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  client:
    name: Client Tests & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Client Dependencies
        run: |
          cd client
          npm install
      - name: Run Client Tests
        run: |
          cd client
          npm test -- --watchAll=false
      - name: Build Client (Optional)
        run: |
          cd client
          npm run build

  server:
    name: Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Server Dependencies
        run: |
          cd server
          npm install
      - name: Run Server Tests
        run: |
          cd server
          npm test
